### ISSUE TITLE
StringIO error during pip3 installation 

### ISSUE THREAD

**Issue by ruffsl** [balena/python-smime#2]
I'm not sure if the release on pip is python3 compatible:
[smime-0.0.1](https://pypi.python.org/pypi/smime/0.0.1) md5: 4ee2f26429865f398767c2a07f83352c
```
$ sudo pip3 install smime
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting smime
  Downloading smime-0.0.1.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 4.4MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jpt8pz6l/smime/setup.py", line 16, in <module>
        version=__import__('smime').__version__,
      File "/tmp/pip-build-jpt8pz6l/smime/smime/__init__.py", line 7, in <module>
        from .encrypt import encrypt
      File "/tmp/pip-build-jpt8pz6l/smime/smime/encrypt.py", line 8, in <module>
        from .rsa import RSAPublicKey
      File "/tmp/pip-build-jpt8pz6l/smime/smime/rsa.py", line 4, in <module>
        from smime.crypto import cert
      File "/tmp/pip-build-jpt8pz6l/smime/smime/crypto/cert.py", line 9, in <module>
        from smime.crypto import pem
      File "/tmp/pip-build-jpt8pz6l/smime/smime/crypto/pem.py", line 4, in <module>
        import StringIO
    ImportError: No module named 'StringIO'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jpt8pz6l/smime/
```

**Comment by balena** [comment]
Hello @ruffsl,

On my side I've got:

```

**Comment by balena** [comment]
@ruffsl, I've just managed to upload a new version `0.0.3` which shall work on your side as well.

**Comment by balena** [comment]
Closing due to inactivity. Reopen if you still find any problems on your side.

**Comment by ruffsl** [comment]
Installation from pip is now working just fine,
Thanks @balena !
